twitter: "https://twitter.com/k2s_15"
github: "https://github.com/k2s09"
linkedin: "https://www.linkedin.com/in/kavin-sood-a36505222"
youtube: "https://www.youtube.com/channel/UCbDUe6VFWHMKcd-NO00SGAg"
dribbble: ""
instagram: "https://www.instagram.com/_kavin.05/"
facebook: ""
medium: "https://medium.com/@moneykavinsood"
patreon: ""
paypal: ""
unsplash: ""
spotify: "https://open.spotify.com/user/amhz6q73edxkvguf9ll92o6go"
